export const ActionTypes = {
  //EDIT USER MODAL OPEN
  EDIT_MODAL_OPEN : 'EDIT_MODAL_OPEN',
  //EDIT USER MODAL CLOSE
  EDIT_MODAL_CLOSE : 'EDIT_MODAL_CLOSE',

  //USERS GET ALL
  USERS_REQUEST: 'USERS_REQUEST',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USERS_ERROR: 'USERS_ERROR',

  //USER CREATE
  USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
  USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
  USER_CREATE_ERROR: 'USER_CREATE_ERROR',

  //UPDATE USER BY ID
  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',


  //DELETE USERS BY ID
  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_ERROR: 'USER_DELETE_ERROR',
};